<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVIje1Ft\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVIje1Ft/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVIje1Ft.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVIje1Ft\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVIje1Ft\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VIje1Ft',
    'container.build_id' => '3006dc47',
    'container.build_time' => 1580382946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVIje1Ft');
