<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2OYY74Y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2OYY74Y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2OYY74Y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2OYY74Y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2OYY74Y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2OYY74Y',
    'container.build_id' => '951db917',
    'container.build_time' => 1580329225,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2OYY74Y');
