<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6mYu3y8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6mYu3y8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6mYu3y8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6mYu3y8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6mYu3y8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6mYu3y8',
    'container.build_id' => 'dc82533f',
    'container.build_time' => 1580385250,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6mYu3y8');
